
package org.engmetrics.gui;

import org.engmetrics.cli.TerminalProcess;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * The main project window class to interact with users
 */
public class StartWindow extends javax.swing.JFrame {

    private File selectedDirectory;

    public StartWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIntro = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        btnUpload = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResults = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Complex Cyclomatic Counter");
        setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        setResizable(false);

        lbIntro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbIntro.setText("Java Project Location:");

        txtLocation.setEditable(false);
        txtLocation.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        btnUpload.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUpload.setMnemonic('C');
        btnUpload.setText("Click here to choose a source code path...");
        btnUpload.setToolTipText("Click here to choose a source code path...");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        btnStart.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnStart.setMnemonic('S');
        btnStart.setText("Start Analysis");
        btnStart.setToolTipText("clicl to start analysisc action");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtResults.setColumns(20);
        txtResults.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtResults.setLineWrap(true);
        txtResults.setRows(5);
        txtResults.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtResults);

        jMenu1.setMnemonic('o');
        jMenu1.setText("Options");
        jMenu1.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        menuAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuAbout.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        menuAbout.setMnemonic('a');
        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        jMenu1.add(menuAbout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStart)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbIntro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(btnUpload))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIntro)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnStart)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
       JFileChooser fc = new JFileChooser();
        fc.setDialogType(JFileChooser.OPEN_DIALOG);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        File initialDir = new File("./");
        fc.setCurrentDirectory(initialDir);
        fc.setDialogTitle("Choose file");
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            this.selectedDirectory = fc.getSelectedFile();
            this.txtLocation.setText(this.selectedDirectory.getAbsolutePath());
            this.txtResults.setText("Folder selected, click on Start Analysis (click and wait).");
        } 
    }//GEN-LAST:event_btnUploadActionPerformed

    /**
     * Start analysis action button, if a file or folder is provided then the analysis will start at this point
     * @param evt 
     */
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        this.btnStart.setEnabled(false);
        if(this.txtLocation.getText().isEmpty()){
            this.txtResults.setText("You need to set a source code path to run this analysis \n");
        
        }else{
            String formatPath = "\"" + this.txtLocation.getText() + "\"";
            TerminalProcess terminal = new TerminalProcess("java -jar", "tools/checkstyle.jar", "tools/config.xml", formatPath);
            boolean success = terminal.runCommand();
            if(success){
                this.txtResults.setText(this.txtResults.getText() + terminal.getOutputText());
            }

            if(!success){
                this.txtResults.setText("Cannot process command line.");
            }
        }
        this.btnStart.setEnabled(true);
        
        
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * Menu item to open an about window
     * @param evt 
     */
    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        AboutWindow about = new AboutWindow();
        about.setLocationRelativeTo(this);
        about.setVisible(true);
    }//GEN-LAST:event_menuAboutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnUpload;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbIntro;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextArea txtResults;
    // End of variables declaration//GEN-END:variables
}
